#+BEGIN_QUOTE
Il y a deux ans (à l'époque où j'écris cet article), j'ai pris la décision de
changer la manière dont je consommais mon café. Depuis, bien qu'étant encore
bien peu expérimenté, j'ai découvert un nouveau monde, goûtu, agréable au nez,
riche et diversifié. Principalement parce que je ne suis pas particulièrement
prolifique dans l'exercice de la rédaction, que mon article sur les émissions
de télévision en rapport á la bande dessinée est, au doigt mouillé (je
ne collecte pas de données sur mes potentiels lecteurs), le plus populaire
de ce site internet et que le sujet m'intéresse (tout de même !), je m'inspire
de [[https://yannickschutz.com/pause-cafe/][Yannick]] pour vous faire part de ma modeste expérience avec le café.

En complément de l'envie de "faire part" des raisons qui m'ont poussé à 
augmenter mon exigence par rapport au café, j'essaierai, dans cet article,
de présenter un très bref résumé (un peu naïf) des astuces qui, selon moi,
permettent de démarrer, et d'un peu de vocabulaire pour faciliter la 
sélection de son café.

Par contre, n'accordons pas à cet article plus d'ambition qu'il n'en prétend,
je pense qu'il existe suffisament de ressources pour retracer l'histoire du
café, géographiquement et socialement, sur le net ou dans des livres. Voyons
plutôt cet article comme un retour d'expérience.
#+END_QUOTE

Alors que je n'ai absolument aucun souvenir de ma première bière ou de mon
premier verre de vin, j'ai un très net souvenir de ma toute première tasse
de café. Est-ce parce que, en toute honnêteté, ce fût une expérience
traumatisante ? Quoi qu'il en soit, en 1998, alors âgé de 9 ans, à l'occasion
de la Saint-Nicolas (une fête d'une importance capitale pour les Belges), je
demande fièrement à mon grand-père maternelle une tasse de café !
Après avoir consulté mes parents, il accède à ma requête, à la condition que
je m'engage à terminer la tasse qu'il me servirait... j'accepte, pour mon
plus grand malheur ! La boisson est amère et je suis incapable de la terminer.
Armé de courage, de sucre et de lait, je me souviens très précisement m'être
battu contre mon palais, mes papilles et mon estomac pour venir à bout de
la boisson maron (et oui, l'abus de lait) en me promettant de ne plus
jamais m'aventurer dans les méandres du café, la boisson était visiblement
incompatible avec mes goûts.

Le café mis de côté, ce n'est que bien plus tard, quand je commencerai à
programmer de nuit que je renouerai avec le café, pour le meilleur et,
dans un premier temps, pour le pire.

*** Voyage avec pour premier aboutissement la monstruosité du café instantané

On s'accorde généralement pour dire que la cafëine tient éveillé. C'est en
partie pour cette raison que j'ai commencé à boire du café. En grandissant,
notre palais s'adapte et nous permet d'apprécier des aliments que l'on avait
du mal à savourer étant plus jeune, le café, l'alcool etc. Supportant le 
goût du café que j'avais à disposition, j'ai commencé à en consommer de plus
en plus pour la pseudo-raison d'être maintenu éveillé. Comme ma consommation
de café n'etait que de l'ordre de l'utilité, mon premier objectif fût
d'optimiser ma prépration, pour aller plus vite et génerer moins de vaisselle
sale. C'est ainsi que j'en suis arrivé à ne consommer qu'exclusivement du café
instantané. Un café peu savoureux, chimique et incroyablement cher.

Même s'il m'arrivait d'être satisfait du goût de certains /espresso/ en
/coffee-shop/, je construisais une distinction mentale très précise entre
le café que je consommais "à l'extérieur" et le café que je faisais chez
moi, imaginant qu'obtenir un "bon café" était hors de mes compétences et de
mon materiel.

*** Le livre du thé

Ironiquement, mon envie de consommer du "bon café" a été motivé par la lecture
du [[https://fr.wikipedia.org/wiki/Le_Livre_du_th%C3%A9][Livre du thé]] de [[https://fr.wikipedia.org/wiki/Okakura_Kakuz%C5%8D][Okakura Kakuzō]], extraordinairement traduit (de mon point
de vue) en Français par le poète [[https://fr.wikipedia.org/wiki/Gabriel_Mourey][Gabriel Mourey]]. "Le livre du thé" est un 
essai écrit en 1906 qui, dans les grandes lignes, faisant des ponts avec
la culture et l'esthétique japonaise, peut faire office de manuel
d'initiation à l'art du thé, au travers de ses différents rituels et de la
cérémonie du service pour les occidentaux. Le livre est, selon moi, 
une lecture recommandable, car elle présente une dimension spirituelle à une 
collection d'actes du quotidien. Même si ma consommation de thé a peu varié
(allez savoir pourquoi, il m'arrivait déjà d'acheter du thé "moins 
industriel" et d'être "un peu informé" sur les températures d'eau, peut-être
parce que la popularité du "Livre du thé" a ancré quelques bonnes pratiques
dans les mœurs), la lecture de ce livre a fait germer dans mon esprit
l'envie d'ajouter à mon quotidien des rituels liés a ma consommation et
à la selection de "produits de spécialités". J'ai pensé, au dam potentiel 
de mes poumons, à faire mûrir ma consommation de tabac. Heureusement, je
n'ai pas réussi à en extraire de rituels. Le café s'est naturellement
présenté comme un autre sujet d'exprérimentation. J'ai donc évoqué,
vaporeusement, l'envie de faire évoluer ma consommation de café, sans
dépasser le stade de l'évocation.

Quelques mois après ces premières évocations, j'ai reçu une cafetière à
piston et j'ai sérieusement commencé à tâcher de me cultiver sur le
café. Avec du recul, je trouve ça assez amusant d'avoir eu l'envie, certes,
peu insistante, de boire du bon  café après avoir lu "Le Livre du thé".


